name: Build, Lint, Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # Needed for the tests
    - name: Set git username
      run: git config --global user.name "some name"

    - name: Install dependencies
      run: cargo build --verbose

    - name: Run Clippy (Linting)
      run: cargo clippy -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run tests
      run: cargo test --verbose
